version: '3'
services:
  eclipse-mosquitto:
    image: eclipse-mosquitto:2.0.15
    restart: always
    user: 101882:1000
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/data/:/mosquitto/data/
      - ./mosquitto/config/:/mosquitto/config/